# 쿠버네티스에서 필요한 볼륨을 요청하는 작업
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc

spec:
  storageClassName: mylocalstorage # PV와 연결되는 이름
  
  resources:
    requests:
      storage: 20Gi # 최소한 20Gi정보의 pv가 필요
  
  accessModes:
    # 옵션이 3개
    # ReadOnlyMany # 다중노드에서 접근해서 읽기 가능
    # ReadWriteMany # 다중노드에서 접근해서 읽기/쓰기가능
    - ReadWriteOnce # 싱글노드에서 읽기/쓰기 가능

--- ## PV(물지저장소)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage

spec:
  storageClassName: mylocalstorage # PVC와 연결되는 이름
  hostPath: 
    path: /mnt/some/new/mydata
    type: DirectoryOrCreate
  
  capacity:
    storage: 20Gi # 여기 용량은 20Gi
  
  accessModes:
    - ReadWriteOnce