apiVersion: v1
kind: Service
metadata:
  name: quiz-app # 프로젝트 명칭
spec:
  selector:
    app: quiz-app # quiz.yaml에서 작성했떤 deployment의 label의 명칭으로 매칭
  ports:
    - name: http
      port: 8182
      nodePort: 30090 # 브라우저가 Node로 접근이 가능하게 하기 위해 사용하는 포트
  type: NodePort