apiVersion: v1
kind: Service
metadata:
  name: coding404-queue

spec:
  selector:
    app: queue
    release: "1"
  
  ports:
    - name: http
      port: 15672
      # targetPort는 생략가능 (port번호로 자동연결)
      nodePort: 30010
    
    - name: endpoint
      port: 5672 # 큐에 메시지를 송수신 하기위한 번호
      # targetPort는 생략가능 (port번호로 자동연결)
      # nodePort를 열지 않으면 외부에서 접근은 불가능
  
  type: NodePort