apiVersion: v1
kind: Service
metadata:
  name: coding404-webapp

spec:
  selector:
    app: webapp # 파드의 label을 가르킴
    release: "0-1"

  ports:
    - name: http # 이름
      port: 80 #서비스 자체의 포트번호
      targetPort: 80 # 뒤에 연결된 pod컨테이너의 포트번호 (만약 생략하면 port와 동일한 값을 가지게 됨)
      nodePort: 30080

  type: NodePort # 외부에서 접근이 가능 함 (ports 속성에 nodePort 번호를 작성)
  # type: ClusterIP # 외부에서 접근하지 못하게 함 (내부 서비스들끼리만 참조할 수 있음)