apiVersion: v1
kind: Pod
metadata:
  name: webapp #파드명
  labels:
    app: webapp  # t서비스와 매칭되는 라벨 이름

spec: # 파드가 가져야할 스펙을 지정
  containers: 
  - name: webapp
    image: coding404/k8s-coding404-webapp-react:v0